name: Docker Image CI

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

jobs:
  tests: 
    runs-on: ubuntu-latest

    steps:
    - name: Hacer checkout
      uses: actions/checkout@v4

    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'

    - name: Instalar dependencias
      run: composer install

    - name: Ejecutar tests con PHPUnit
      run: vendor/bin/phpunit --testdox tests

  construir:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - name: Hacer checkout
      uses: actions/checkout@v4

    - name: Obtener el tag
      uses: olegtarasov/get-tag@v2.1.4
      id: tagName

    - name: Verificar el tag obtenido
      run: |
        echo "Tag: ${{ steps.tagName.outputs.tag }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ secrets.DOCKER_USER }}/calculadora:${{ steps.tagName.outputs.tag }}
